---
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  # concourse:
  #   image: concourse/concourse
  #   command: quickstart
  #   privileged: true
  #   depends_on: [concourse-db]
  #   ports: ["8080:8080"]
  #   environment:
  #     CONCOURSE_POSTGRES_HOST: concourse-db
  #     CONCOURSE_POSTGRES_USER: concourse_user
  #     CONCOURSE_POSTGRES_PASSWORD: concourse_pass
  #     CONCOURSE_POSTGRES_DATABASE: concourse
  #     CONCOURSE_EXTERNAL_URL: http://localhost:8080
  #     CONCOURSE_ADD_LOCAL_USER: test:test
  #     CONCOURSE_MAIN_TEAM_LOCAL_USER: test
  #     # instead of relying on the default "detect"
  #     CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
  #     CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
  #     CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
  #     CONCOURSE_X_FRAME_OPTIONS: allow
  #     CONCOURSE_CONTENT_SECURITY_POLICY: "*"
  #     CONCOURSE_CLUSTER_NAME: tutorial
  #     CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
  #     CONCOURSE_WORKER_RUNTIME: "containerd"
  #     CONCOURSE_RUNTIME: containerd
  #   volumes:
  #     - ./concourse_entrypoint.sh:/usr/local/bin/entrypoint.sh

  web:
    image: concourse/concourse
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./concourse-docker/keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    links: [web]
    volumes: ["./concourse-docker/keys/worker:/concourse-keys"]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      # enable DNS proxy to support Docker's 127.x.x.x DNS server
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"


  #oncourse_1     | 
  # time="2022-01-12T15:03:15.957228712Z" 
  # level=error msg="failed to enable controllers ([cpuset cpu io memory hugetlb pids rdma])" 
  # error="failed to write subtree controllers [cpuset cpu io memory hugetlb pids rdma] to \"/sys/fs/cgroup/cgroup.subtree_control\": write /sys/fs/cgroup/cgroup.subtree_control: operation not supported"