---
resources:
    - name: repo
      type: git
      source:
          uri: https://github.com/orionrobots/python_usb_robot_arm.git

jobs:
    - name: lint_arm
      plan:
          - get: repo
            trigger: true
          - task: lint
            config:
            platform: linux
            image_resource:
                type: registry-image
                source:
                    repository: python
                    tag: 3.10.1-bullseye
            inputs:
                - name: repo
            run:
                path: sh
                args:
                    - "-cx"
                    - |
                      # setup python
                      python -m pip install --upgrade pip
                      python -m pip install flake8 pytest
                      python -m pip install -e .

                      # run the test
                      # stop the build if there are Python syntax errors or undefined names
                      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
