---
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/odmsolutions/tutorial_environment.git

jobs:

  - name: python-lint
    plan:
      - get: repo
        trigger: true

      - task: lint
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: karlkfi/concourse-dcind
          inputs:
            - name: repo
          run:
            # path: repo/karlkfi_entrypoint.sh
            path: entrypoint.sh

            args:
              - bash
              - -ceux
              - |
                cd repo
                bin/python-lint
